### ISSUE TITLE
Values with a comma are seperated into two values when uploading a timeseries

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#124]
By uploading a timeseries with values that include a comma the tool seperates these values into two values. This problem does not occur when the values are given with a dott. However, I think the majority of our current users will use timeseries where the values are given with a comma. We should find a solution where we either have a warning message when the timeseries includes values with a comma or enable the tool to identify these values and upload the timeseries correct.

**Comment by Bachibouzouk** [comment]
Formating is killing productivity ^^ 

Did you upload an excel file or a csv? If you uploaded a csv what was the separator between values then? (if commas are used as decimal separator)

This can be solved to try first to check if ; is present, if it is, then split values with;, otherwise try with ,

**Comment by FredericHirschmueller** [comment]
I uploaded a csv and after I realized the wrong formatting I changed the comma into a dott.

I would say that we add a warning or a hint when uploading a timeseries, because I would imagine that not every user is aware of this effect.
