### ISSUE TITLE
Add pre-commit hook for linting

### ISSUE THREAD

**Issue by 4lm** [open-plan-tool/gui#215]
- [x] add pre-commit hook
- [x] exclude certain files, e.g. auto-generated migration files
- [x] homogenize CI workflow with pre-commit hook

**Comment by 4lm** [comment]
I'm running into issues, where I push stuff and the linter rejects it remote, linting should IMO happen also locally before commiting via a pre-commit hook.

**Comment by Bachibouzouk** [comment]
This is not an issue that the linter fails, it has lowest prio over features (especially because changing package now will lead to having to spend time making sure the online tool works well and I don't have that time until the workshop), you will have to live with the uncomfortable feeling of seeing test failing on CI ^^ 

I will nevertheless merge those changes after the stakeholder workshop

**Comment by 4lm** [comment]
> This is not an issue that the linter fails, it has lowest prio over features (especially because changing package now will lead to having to spend time making sure the online tool works well and I don't have that time until the workshop), 

OK, thanks for the insides!

>  you will have to live with the uncomfortable feeling of seeing test failing on CI ^^

Ok, I can live with failing linter + failing unit tests

> I will nevertheless merge those changes after the stakeholder workshop

Ok, sounds good!
