### ISSUE TITLE
bug in optimizing PV capacity

### ISSUE THREAD

**Issue by mstich0** [open-plan-tool/gui#248]
When having an actual timeseries for PV-Generation instead of [1 for all timesteps] the optimization does not build maximum capacity, though maximum capacity is clearly the real optimum. 
When increasing the maximum capacity the optimization is also increasing the built capacity but again not up to the maximum. This seems to happen when the minimum of the PV-timeseries is below 1. When I add one value that is eaxactly 1 at any single timestep of the timeseries, optimization results indeed in the maximium PV-capacity allowed.
If any value in the timeseries is above 1 it will exceed the given limit. 
It seems that MVS internally norming the timeseries in some kind of way, while the timeseries given in open-plan should already have the correct value in kWh/kWp.

e.g. with 1 timeseries value at 1.5 --> optimization exceed limit of 100,000
![Image](https://user-images.githubusercontent.com/105202247/250477602-38f8d120-64bc-4d12-84af-dcd63f950a3c.png)

**Comment by Bachibouzouk** [comment]
> instead of [1 for all timesteps]

I am not sure what you mean by this: do you mean that the value does not exceed 1 at any given timestep? Or that the value is a constant (1) at all timesteps?

If you could provide the json file of your example it would be easier to debug :)

**Comment by Bachibouzouk** [comment]
I found the origin of the behavior : https://github.com/rl-institut/multi-vector-simulator/issues/962 now the question is how to change it, I will wait for more comment of the initial developers of MVS

**Comment by Bachibouzouk** [comment]
> It seems that MVS internally norming the timeseries in some kind of way, while the timeseries given in open-plan should already have the correct value in kWh/kWp.

In that case when you set the timeseries to 0.5 constant value, it should comply with kWh/KWp, yet the result is investment in only 0.5 of the maximum capacity.

We need to consider a test case with initial capacity as well to make sure MVS provides correct behavior not overshooting maximum cap when adding optimized cap and installed cap.

I think the answer lies exactly where you thought it would : there seem to be a confusion between timeseries peak taken before or after the normalization. I think oemof requires values between 0 and 1 but does not require that 1 is there in the timeseries. 

This means that the open_plan user could provide a timeseries in kWh and additionally a kWp parameter to format the timeseries to kWh/kWp before sending it to MVS, otherwise the timeseries would by default be normalized by its max

**Comment by mstich0** [comment]
Alright the fix seems to have solved the issue, thanks a lot!
