### ISSUE TITLE
[Tool-view] View after clicking on "Run simulation" button

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#34]
**Bachibouzouk commented 15 days ago**

Once the user click on "Run simulation" the simulation's parameter are sent to the MVS server and processed. So long there is no error or success, the status of the simulation is "pending"

The view to which one is redirected could be:

the same view where the button was clicked with some information about the simulation results being pending (the status could automatically update every 10 or 30seconds)

On this view the error message could also be displayed if any and a link to a pre-filled feedback form describing the error (so if the user do not understand the error they can ask help)

On this page there could be a button to link to the results page if the simulation is successful

It should be explicit that a simulation has run and it should be able to run a simulation again, thus overwriting the present results, in case of success

The view with all projects currently displays a "results" button next to the scenario name. This should be greyed out if no simulation where ran and take the status of the simulation into account (i.e. display "error"/"pending")

**catcad commented 15 days ago**

Hi,
I agree to your suggestions. I think the user should receive sth. like "the simulation was successful!" for the positive user experience.
One question: Is it also possible that the simulation has no output results because contraints prevent the identification of a solution? Then this should become clear to the user that his/her inputs lead to that and that changing those (e.g. reducing min. RE share) and rerun would be a solution.

**Comment by Bachibouzouk** [comment]
From @FredericHirschmueller in #95

After clicking on the "run simualtion" button an other button appears to check the status. This button leads to an other page where the JSON file is displayed and the status is shown on this page.

1. Even when the status in the JSON file shows "DONE" the simulation page doesn't change to "DONE" and the result page is not accessible.

2. When one clicks on the "check status" button it would be better to stay at this page and not display the JSON file, because this might be confusing. It would be better to just refresh the simulation page and update the status. When status changes to "DONE" a button to the result page should appear that leads to the result page.

**Comment by Bachibouzouk** [comment]
Just drafting my thoughts on it here, it will help me fixing this.

The reason why status is not updated even though the simulation is done on mvs_server is because once the user clicks on "Run simulation" a task scheduler is started to check the status of the simulation on the mvs_server. It does so only every minute (not possible to make it go faster unfortunately).

I could implement a check of the simulation status in the "after-simulation" page, so that the results are transfered if the simulation is already done and the task scheduler is stopped. We could then add a message letting the users know they can refresh the page themselves or it is done automatically every minute

**Comment by Bachibouzouk** [comment]
I managed to do implement a period check of the status (every X seconds) in #104
